version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5438:5432"
    volumes:
      - ./scripts/initdb:/docker-entrypoint-initdb.d
      - ../common/data:/opt/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@machine.pes
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
      PGADMIN_DISABLE_POSTFIX: 1
    ports:
      - "8502:80"
    depends_on:
      - db
    volumes:
      - ./config/pgadmin/servers.json:/pgadmin4/servers.json
