version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./scripts/docker/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      CSV_DATA: "agents|/opt/data/csv/agents.csv;customers|/opt/data/csv/customers.csv;calls|/opt/data/csv/calls.csv"
    volumes:
      - ./scripts/initdb:/docker-entrypoint-initdb.d
      - ../data:/opt/data
    ports:
      - "8504:8080"
