version: '3'

services:
  db:
    image: horizoncrafts/mssql-with-initdb
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
      SA_PASSWORD: P@ssw0rd
    ports:
      - "1438:1433"
    volumes:
      - ./scripts/initdb:/docker-entrypoint-initdb.d
      - ../data:/opt/data

