version: "3.9"

services:
  pyside2app:
    build: .
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DISPLAY=$DISPLAY
    volumes:
      - ./src:/opt/src
      - /tmp/.X11-unix:/tmp/.X11-unix
