version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3308:3306"
    volumes:
      - ./config/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./scripts/initdb:/docker-entrypoint-initdb.d
      - ./data:/opt/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8501:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    depends_on:
      - db
