add-recipe-for-hello-world-rocky-8-5:
    # Folder name (i.e. centos-7 or debian-latest)
    # Dockerfile image and tag (i.e. centos:7 or debian:latest)
    # Container image name (i.e. recipes_centos_7_hello_world_image)
	# Operating system )(i.e. Centos 7)
	python hello-world/add_recipe.py \
			"rocky-8-5" \
			"rockylinux:8.5" \
			"recipes_rocky_8_5_hello_world_image" \
			"Rocky 8.5"

add-recipe-for-hello-world-rocky-8-6:
    # Folder name (i.e. centos-7 or debian-latest)
    # Dockerfile image and tag (i.e. centos:7 or debian:latest)
    # Container image name (i.e. recipes_centos_7_hello_world_image)
	# Operating system )(i.e. Centos 7)
	python hello-world/add_recipe.py \
			"rocky-8-6" \
			"rockylinux:8.6" \
			"recipes_rocky_8_6_hello_world_image" \
			"Rocky 8.6"

add-recipe-for-hello-world-rocky-9:
    # Folder name (i.e. centos-7 or debian-latest)
    # Dockerfile image and tag (i.e. centos:7 or debian:latest)
    # Container image name (i.e. recipes_centos_7_hello_world_image)
	# Operating system )(i.e. Centos 7)
	python hello-world/add_recipe.py \
			"rocky-9" \
			"rockyli nux:9" \
			"recipes_rocky_9_hello_world_image" \
			"Rocky 9"

add-recipe-for-office-to-pdf-debian-latest:
    # Folder name (i.e. centos-7 or debian-latest)
    # Dockerfile image and tag (i.e. centos:7 or debian:latest)
    # Container image name (i.e. recipes_centos_7_hello_world_image)
	# Operating system (i.e. Centos 7)
	# Recipe slug (i.e. office-to-pdf)
	# Recipe title (i.e. Office to PDF)
	# Dockerfile installation line (i.e. apt update && apt -y install libreoffice)
	python office-to-pdf/add_recipe.py \
			"debian-latest" \
			"debian:latest" \
			"recipes_debian_latest_office_to_pdf_image" \
			"Debian Latest" \
			"office-to-pdf" \
			"Office to PDF" \
			"apt update && apt install -y --no-install-recommends libreoffice default-jre"

add-recipe-for-office-to-pdf-ubuntu-latest:
    # Folder name (i.e. centos-7 or debian-latest)
    # Dockerfile image and tag (i.e. centos:7 or debian:latest)
    # Container image name (i.e. recipes_centos_7_hello_world_image)
	# Operating system (i.e. Centos 7)
	# Recipe slug (i.e. office-to-pdf)
	# Recipe title (i.e. Office to PDF)
	# Dockerfile installation line (i.e. apt update && apt -y install libreoffice)
	python office-to-pdf/add_recipe.py \
			"ubuntu-latest" \
			"ubuntu:latest" \
			"recipes_ubuntu_latest_office_to_pdf_image" \
			"Ubuntu Latest" \
			"office-to-pdf" \
			"Office to PDF" \
			"apt update && apt install -y --no-install-recommends libreoffice default-jre"
