add-recipe-for-hello-world-rocky-8-5:
    # Folder name (i.e. centos-7 or debian-latest)
    # Dockerfile image and tag (i.e. centos:7 or debian:latest)
    # Container image name (i.e. recipes_centos_7_hello_world_image)
	# Operating system )(i.e. Centos 7)
	python hello-world/add_recipe.py \
			"rocky-8-5" \
			"rockylinux:8.5" \
			"recipes_rocky_8_5_hello_world_image" \
			"Rocky 8.5"

add-recipe-for-hello-world-rocky-8-6:
    # Folder name (i.e. centos-7 or debian-latest)
    # Dockerfile image and tag (i.e. centos:7 or debian:latest)
    # Container image name (i.e. recipes_centos_7_hello_world_image)
	# Operating system )(i.e. Centos 7)
	python hello-world/add_recipe.py \
			"rocky-8-6" \
			"rockylinux:8.6" \
			"recipes_rocky_8_6_hello_world_image" \
			"Rocky 8.6"

add-recipe-for-hello-world-rocky-9:
    # Folder name (i.e. centos-7 or debian-latest)
    # Dockerfile image and tag (i.e. centos:7 or debian:latest)
    # Container image name (i.e. recipes_centos_7_hello_world_image)
	# Operating system )(i.e. Centos 7)
	python hello-world/add_recipe.py \
			"rocky-9" \
			"rockylinux:9" \
			"recipes_rocky_9_hello_world_image" \
			"Rocky 9"
